***API Data (Customer Details)***

Fetch customer details from a mock API: https://dummyjson.com/users
print first two rows.

-The requests library is used to send HTTP requests in Python.

-It helps retrieve data from web APIs (Application Programming Interfaces).

-requests.get(url): Sends an HTTP GET request to the given URL ("https://dummyjson.com/users").

-The response from the server contains user data in JSON format.

-customers = response.json()  

-.json() converts the API response from JSON format to a Python dictionary.

-customers is now a Python dictionary containing user data.

-The "users" key contains a list of user dictionaries.

-By using "users" key we can print first two rows.

In [3]:
import requests

response = requests.get("https://dummyjson.com/users")  
customers = response.json()  

# Extract the user list and print first two
print(customers["users"][:2])

[{'id': 1, 'firstName': 'Emily', 'lastName': 'Johnson', 'maidenName': 'Smith', 'age': 28, 'gender': 'female', 'email': 'emily.johnson@x.dummyjson.com', 'phone': '+81 965-431-3024', 'username': 'emilys', 'password': 'emilyspass', 'birthDate': '1996-5-30', 'image': 'https://dummyjson.com/icon/emilys/128', 'bloodGroup': 'O-', 'height': 193.24, 'weight': 63.16, 'eyeColor': 'Green', 'hair': {'color': 'Brown', 'type': 'Curly'}, 'ip': '42.48.100.32', 'address': {'address': '626 Main Street', 'city': 'Phoenix', 'state': 'Mississippi', 'stateCode': 'MS', 'postalCode': '29112', 'coordinates': {'lat': -77.16213, 'lng': -92.084824}, 'country': 'United States'}, 'macAddress': '47:fa:41:18:ec:eb', 'university': 'University of Wisconsin--Madison', 'bank': {'cardExpire': '03/26', 'cardNumber': '9289760655481815', 'cardType': 'Elo', 'currency': 'CNY', 'iban': 'YPUXISOBI7TTHPK2BR3HAIXL'}, 'company': {'department': 'Engineering', 'name': 'Dooley, Kozey and Cronin', 'title': 'Sales Manager', 'address': {'address': '263 Tenth Street', 'city': 'San Francisco', 'state': 'Wisconsin', 'stateCode': 'WI', 'postalCode': '37657', 'coordinates': {'lat': 71.814525, 'lng': -161.150263}, 'country': 'United States'}}, 'ein': '977-175', 'ssn': '900-590-289', 'userAgent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36', 'crypto': {'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a', 'network': 'Ethereum (ERC20)'}, 'role': 'admin'}, {'id': 2, 'firstName': 'Michael', 'lastName': 'Williams', 'maidenName': '', 'age': 35, 'gender': 'male', 'email': 'michael.williams@x.dummyjson.com', 'phone': '+49 258-627-6644', 'username': 'michaelw', 'password': 'michaelwpass', 'birthDate': '1989-8-10', 'image': 'https://dummyjson.com/icon/michaelw/128', 'bloodGroup': 'B+', 'height': 186.22, 'weight': 76.32, 'eyeColor': 'Red', 'hair': {'color': 'Green', 'type': 'Straight'}, 'ip': '12.13.116.142', 'address': {'address': '385 Fifth Street', 'city': 'Houston', 'state': 'Alabama', 'stateCode': 'AL', 'postalCode': '38807', 'coordinates': {'lat': 22.815468, 'lng': 115.608581}, 'country': 'United States'}, 'macAddress': '79:15:78:99:60:aa', 'university': 'Ohio State University', 'bank': {'cardExpire': '02/27', 'cardNumber': '6737807858721625', 'cardType': 'Elo', 'currency': 'SEK', 'iban': '83IDT77FWYLCJVR8ISDACFH0'}, 'company': {'department': 'Support', 'name': 'Spinka - Dickinson', 'title': 'Support Specialist', 'address': {'address': '395 Main Street', 'city': 'Los Angeles', 'state': 'New Hampshire', 'stateCode': 'NH', 'postalCode': '73442', 'coordinates': {'lat': 79.098326, 'lng': -119.624845}, 'country': 'United States'}}, 'ein': '912-602', 'ssn': '108-953-962', 'userAgent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/97.0.1072.76 Safari/537.36', 'crypto': {'coin': 'Bitcoin', 'wallet': '0xb9fc2fe63b2a6c003f1c324c3bfa53259162181a', 'network': 'Ethereum (ERC20)'}, 'role': 'admin'}]

***Store All API Data in SQL Server & CSV***

The below script:

-Fetches all fields from the JSON.

-Dynamically creates a table with all columns.

-Inserts all data into SQL Server.

-Saves full data to a CSV file.

-requests: Fetches data from the API.

-pyodbc: Connects to SQL Server.

-pandas: Handles and stores data in a CSV file.

-Establishes a connection to the SQL Server using ODBC driver.

-Creates a cursor to interact with the database.

-Sends a GET request to the API endpoint.

-If successful (status code 200), the user data is extracted and stored in a list.

-Checks if the "Users" table already exists.

-Creates the table with specified columns if it doesn't exist.

-Iterates through the user data and inserts each user record into the SQL Server "Users" table.

-Retrieves the stored user data from SQL Server using SQL query.

-Saves the data as a CSV file to the specified location.

-Closes the connection to the SQL Server.

-Prints a success message when the data extraction and storage are complete.

In [4]:
import requests
import pyodbc
import pandas as pd

# Database connection details
server = 'JYOTHI\\SQLEXPRESS'   
database = 'dataExtraction'
driver = '{ODBC Driver 17 for SQL Server}'

# Establish SQL Server Connection
conn = pyodbc.connect(f'DRIVER={driver};SERVER={server};DATABASE={database};Trusted_Connection=yes;')
cursor = conn.cursor()

# Fetch full data from API
api_url = "https://dummyjson.com/users"
response = requests.get(api_url)

if response.status_code == 200:
    users = response.json()["users"]  # Extract full users list
else:
    print("Failed to fetch data from API")
    exit()

# Create Table for All Fields (Dynamically)
cursor.execute("""
IF NOT EXISTS (SELECT * FROM sysobjects WHERE name='Users' AND xtype='U')
CREATE TABLE Users (
    id INT PRIMARY KEY,
    firstName NVARCHAR(100),
    lastName NVARCHAR(100),
    maidenName NVARCHAR(100),
    age INT,
    gender NVARCHAR(20),
    email NVARCHAR(255),
    phone NVARCHAR(50),
    username NVARCHAR(100),
    password NVARCHAR(255),
    birthDate DATE,
    image NVARCHAR(255),
    bloodGroup NVARCHAR(10),
    height FLOAT,
    weight FLOAT,
    eyeColor NVARCHAR(50),
    hairColor NVARCHAR(50),
    hairType NVARCHAR(50),
    ip NVARCHAR(50),
    macAddress NVARCHAR(50),
    university NVARCHAR(255),
    city NVARCHAR(100),
    state NVARCHAR(100),
    stateCode NVARCHAR(10),
    postalCode NVARCHAR(20),
    country NVARCHAR(100),
    cardNumber NVARCHAR(50),
    cardType NVARCHAR(50),
    currency NVARCHAR(10),
    iban NVARCHAR(50),
    company NVARCHAR(255),
    jobTitle NVARCHAR(255),
    ein NVARCHAR(50),
    ssn NVARCHAR(50),
    coin NVARCHAR(50),
    wallet NVARCHAR(255),
    network NVARCHAR(50),
    role NVARCHAR(50)
)
""")
conn.commit()

# Insert Full API Data into SQL Server
for user in users:
    cursor.execute("""
    INSERT INTO Users (
        id, firstName, lastName, maidenName, age, gender, email, phone, 
        username, password, birthDate, image, bloodGroup, height, weight, 
        eyeColor, hairColor, hairType, ip, macAddress, university, 
        city, state, stateCode, postalCode, country, cardNumber, 
        cardType, currency, iban, company, jobTitle, ein, ssn, coin, 
        wallet, network, role
    ) 
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    """, (
        user["id"], user["firstName"], user["lastName"], user["maidenName"], user["age"], 
        user["gender"], user["email"], user["phone"], user["username"], user["password"], 
        user["birthDate"], user["image"], user["bloodGroup"], user["height"], user["weight"], 
        user["eyeColor"], user["hair"]["color"], user["hair"]["type"], user["ip"], 
        user["macAddress"], user["university"], user["address"]["city"], 
        user["address"]["state"], user["address"]["stateCode"], user["address"]["postalCode"], 
        user["address"]["country"], user["bank"]["cardNumber"], user["bank"]["cardType"], 
        user["bank"]["currency"], user["bank"]["iban"], user["company"]["name"], 
        user["company"]["title"], user["ein"], user["ssn"], 
        user["crypto"]["coin"], user["crypto"]["wallet"], user["crypto"]["network"], 
        user["role"]
    ))

conn.commit()

# Step 4: Fetch Data and Save to CSV
df = pd.read_sql("SELECT * FROM Users", conn)
df.to_csv("C:/Users/jyoth/Data-Extraction-Project/data/users_API_data.csv", index=False)

# Close connection
conn.close()

print("Data successfully extracted and stored in SQL Server & CSV!")

Data successfully extracted and stored in SQL Server & CSV!

C:\Users\jyoth\AppData\Local\Temp\ipykernel_36224\3776510391.py:99: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql("SELECT * FROM Users", conn)